var baseUrl = '';
var serverUrl = 'https://mlearning-tools-api.pingan.com.cn/server';
var appId = 'wx784c0c8df021be32';
var courseWareJson = {
    "courseIntroduction": "",
    "previewUrl": "cwtools/courseware/2021-11-21/120FFF08B4B345E7ACFC919BE6E77BEB/index.html",
    "keywords": "",
    "animationAll": "none",
    "mainTimeOpen": true,
    "templateId": "0",
    "autoSave": false,
    "courseSource": "",
    "animationList": ["", "", ""],
    "isAssess": true,
    "costTime": "",
    "coverPicLzkCwSrc": "",
    "showType": "2",
    "courseId": "120FFF08B4B345E7ACFC919BE6E77BEB",
    "learnedSetting": "0",
    "cwType": "videohtml5",
    "showPageNo": false,
    "courseName": "给圈圈的情书",
    "createdDate": "2021-11-21",
    "courseDeveloper": "",
    "bgMusic": {"audioLzkSrc": "", "audioName": "", "materialId": ""},
    "reviewStatus": "0",
    "loadPage":
        {
            "isCurrentPage":true,
            "groupCompList": [],
            "groupListInfo": [],
            "modelId": "",
            "totalTime": 10,
            "componentList": [{
                "filterStyle": {"filter": "", "background": "transparent", "mixBlendMode": ""},
                "compType": "pictureComp",
                "cost": 10,
                "compStyle": {
                    "rotate": "0",
                    "border_width": "0px",
                    "z_index": 1,
                    "turnY": 1,
                    "turn": 1,
                    "border_color": "rgba(0,0,0,1)",
                    "top": "20.000000000000004px",
                    "left": "7.000000000000001px",
                    "transparency": 1,
                    "width": "167px",
                    "opacity": 1,
                    "border_radius": "0px",
                    "box_shadow": "",
                    "height": "68.00000000000001px"
                },
                "pictureLzkSrc": "cwtools/material/private/20171109/tnxl15102355991425083.png",
                "unique": "52022f83c9854e62ac602ffc81a983b6",
                "belongTo": "",
                "clipStyle": {"isClipPic": false, "w": 0, "x": 0, "h": 0, "y": 0, "clipType": "", "clipRatio": ""},
                "isSelect": true,
                "materialId": "",
                "begin": 0,
                "animation": {
                    "typeIn": "",
                    "typeOut": "",
                    "emphasisTime": 0.5,
                    "emphasisType": "",
                    "isLoop": false,
                    "typeInTime": 0.5,
                    "typeOutTime": 0.5
                }
            }, {
                "filterStyle": {"filter": "", "background": "transparent", "mixBlendMode": ""},
                "compType": "pictureComp",
                "cost": 10,
                "compStyle": {
                    "rotate": "0",
                    "border_width": "0px",
                    "z_index": 2,
                    "turnY": 1,
                    "turn": 1,
                    "border_color": "rgba(0,0,0,1)",
                    "top": "107.00000000000001px",
                    "left": "76px",
                    "transparency": 1,
                    "width": "129px",
                    "opacity": 1,
                    "border_radius": "0px",
                    "box_shadow": "",
                    "height": "119px"
                },
                "pictureLzkSrc": "cwtools/material/private/20171109/tn5h151023538100170761.png",
                "unique": "fc494aed33724fa08c240d2321e2573e",
                "belongTo": "",
                "clipStyle": {"isClipPic": false, "w": 0, "x": 0, "h": 0, "y": 0, "clipType": "", "clipRatio": ""},
                "isSelect": true,
                "materialId": "",
                "begin": 0,
                "animation": {
                    "typeIn": "",
                    "typeOut": "",props: ['pageData','pageImageStyle','currentPageNo','currentTime','courseWare','totalTime','loadPageNo','sendPostAjax','userInfo','clientHeight','isPreview'],

                    "emphasisTime": 0.5,
                    "emphasisType": "",
                    "isLoop": false,
                    "typeInTime": 0.5,
                    "typeOutTime": 0.5
                }
            }, {
                "filterStyle": {"filter": "", "background": "transparent", "mixBlendMode": ""},
                "compType": "pictureComp",
                "cost": 10,
                "compStyle": {
                    "rotate": "0",
                    "border_width": "0px",
                    "z_index": 3,
                    "turnY": 1,
                    "turn": 1,
                    "border_color": "rgba(0,0,0,1)",
                    "top": "220.00000000000003px",
                    "left": "56.00000000000001px",
                    "transparency": 1,
                    "width": "101.00000000000001px",
                    "opacity": 1,
                    "border_radius": "0px",
                    "box_shadow": "",
                    "height": "105.00000000000001px"
                },
                "pictureLzkSrc": "cwtools/material/private/20171109/tnkv151023559096543606.png",
                "unique": "46cd6a1021af4f76a431819a7ed0301e",
                "belongTo": "",
                "clipStyle": {"isClipPic": false, "w": 0, "x": 0, "h": 0, "y": 0, "clipType": "", "clipRatio": ""},
                "isSelect": true,
                "materialId": "",
                "begin": 0,
                "animation": {
                    "typeIn": "",
                    "typeOut": "",
                    "emphasisTime": 0.5,
                    "emphasisType": "",
                    "isLoop": false,
                    "typeInTime": 0.5,
                    "typeOutTime": 0.5
                }
            }, {
                "filterStyle": {"filter": "", "background": "transparent", "mixBlendMode": ""},
                "compType": "pictureComp",
                "cost": 10,
                "compStyle": {
                    "rotate": "0",
                    "border_width": "0px",
                    "z_index": 4,
                    "turnY": 1,
                    "turn": 1,
                    "border_color": "rgba(0,0,0,1)",
                    "top": "382.00000000000006px",
                    "left": "114.00000000000001px",
                    "transparency": 1,
                    "width": "132px",
                    "opacity": 1,
                    "border_radius": "0px",
                    "box_shadow": "",
                    "height": "129px"
                },
                "pictureLzkSrc": "cwtools/material/private/20171109/tny4151023559691231287.png",
                "unique": "8a4982334892408680785f439e4f701d",
                "belongTo": "",
                "clipStyle": {"isClipPic": false, "w": 0, "x": 0, "h": 0, "y": 0, "clipType": "", "clipRatio": ""},
                "isSelect": true,
                "materialId": "",
                "begin": 0,
                "animation": {
                    "typeIn": "",
                    "typeOut": "",
                    "emphasisTime": 0.5,
                    "emphasisType": "",
                    "isLoop": false,
                    "typeInTime": 0.5,
                    "typeOutTime": 0.5
                }
            }, {
                "filterStyle": {"filter": "", "background": "transparent", "mixBlendMode": ""},
                "compType": "pictureComp",
                "cost": 10,
                "compStyle": {
                    "rotate": "0",
                    "border_width": "0px",
                    "z_index": 5,
                    "turnY": 1,
                    "turn": 1,
                    "border_color": "rgba(0,0,0,1)",
                    "top": "309px",
                    "left": "-44.00000000000001px",
                    "transparency": 1,
                    "width": "176.00000000000003px",
                    "opacity": 1,
                    "border_radius": "0px",
                    "box_shadow": "",
                    "height": "202.00000000000003px"
                },
                "pictureLzkSrc": "cwtools/material/private/20171109/tnf7151023559450690586.png",
                "unique": "ed2517a082324d5eb803c9d8a327ccd9",
                "belongTo": "",
                "clipStyle": {"isClipPic": false, "w": 0, "x": 0, "h": 0, "y": 0, "clipType": "", "clipRatio": ""},
                "isSelect": true,
                "materialId": "",
                "begin": 0,
                "animation": {
                    "typeIn": "",
                    "typeOut": "",
                    "emphasisTime": 0.5,
                    "emphasisType": "",
                    "isLoop": false,
                    "typeInTime": 0.5,
                    "typeOutTime": 0.5
                }
            }],
            "active": "",
            "changeTextStyle": 0,
            "video": [],
            "pageId": "loadPageId",
            "currentTime": 0,
            "pageType": "slide",
            "bgImageStyle": {"bgImagePosition": "", "bgImageSize": "", "bgImageLzkSrc": "", "materialId": ""},
            "themeColor": "rgba(255,255,255,0)",
            "pageNo": -1,
            "action": "",
            "audio": [],
            "changeFlag": 0,
            "gridFlag": false
        }
    ,
    "pageList": [{
        "groupCompList": [],
        "groupListInfo": [{
            "sublistInfo": [{
                "compType": "shapeComp",
                "unique": "c45067f2f94343ceb0756d695627fc44"
            }, {"compType": "wordComp", "unique": "8f6cbb53395640dda442ec4fdffdea11"}, {
                "compType": "wordComp",
                "unique": "41721e8c7fb147f48528d143daf8a215"
            }, {"compType": "wordComp", "unique": "aef32e89e5c744a589a881d0cb122eb6"}, {
                "compType": "wordComp",
                "unique": "ca9d6992834f4ed0a277ead8e9655202"
            }, {"compType": "shapeComp", "unique": "754a38a493d94d94a8837ccb28c5c4a8"}],
            "unique": "879b69c28e894fbb848de890ae32d42a"
        }],
        "modelId": "",
        "totalTime": 10,
        "componentList": [{
            "subsetCompList": [{
                "compType": "shapeComp",
                "cost": 10,
                "compStyle": {
                    "rotate": "0",
                    "border_width": "0px",
                    "z_index": 1,
                    "turnY": 1,
                    "fillList": ["#2f302f"],
                    "turn": 1,
                    "border_color": "rgba(0,0,0,1)",
                    "fill": "#2f302f",
                    "opacityList": ["1"],
                    "top": "14.544648327359974px",
                    "left": "0px",
                    "transparency": 1,
                    "width": "259.121351981527px",
                    "opacity": 1,
                    "border_radius": "0px",
                    "box_shadow": "",
                    "height": "137.73892464134332px"
                },
                "unique": "c45067f2f94343ceb0756d695627fc44",
                "belongTo": "879b69c28e894fbb848de890ae32d42a",
                "isSelect": true,
                "materialId": "10650DE7F2184EB7A6AD0DF6C6A61C8F",
                "shapesvg": "%3Csvg%20width%3D%22100%25%22%20height%3D%22100%25%22%20style%3D%22fill%3Argb(47%2C48%2C47)%3Bfill-opacity%3A1%22%20id%3D%22%E5%9B%BE%E5%B1%82_3%22%20data-name%3D%22%E5%9B%BE%E5%B1%82%203%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20301%20160%22%20data-color0%3D%22color%22%3E%3Ctitle%3E3%3C%2Ftitle%3E%3Cpolygon%20points%3D%22299%202%20299%20158%202%20158%202%202%2046%202%2046%200%200%200%200%20160%20301%20160%20301%200%20254%200%20254%202%20299%202%22%3E%3C%2Fpolygon%3E%3C%2Fsvg%3E",
                "begin": 0,
                "animation": {
                    "typeIn": "",
                    "typeOut": "",
                    "emphasisTime": 0,
                    "emphasisType": "",
                    "isLoop": false,
                    "typeInTime": 0.5,
                    "typeOutTime": 0.5
                }
            }, {
                "compCoverIsShow": false,
                "cost": 10,
                "compStyle": {
                    "rotate": "0",
                    "z_index": 2,
                    "top": "12.466841423451406px",
                    "left": "10.389034519542836px",
                    "width": "244.14231120925666px",
                    "opacity": 1
                },
                "isSelect": true,
                "animation": {
                    "typeIn": "",
                    "typeOut": "",
                    "emphasisTime": 0,
                    "emphasisType": "",
                    "isLoop": false,
                    "typeInTime": 0.5,
                    "typeOutTime": 0.5
                },
                "compType": "wordComp",
                "bgColor": "rgba(255,255,255,0)",
                "unique": "8f6cbb53395640dda442ec4fdffdea11",
                "belongTo": "879b69c28e894fbb848de890ae32d42a",
                "editStyle": {
                    "textHeight": "16px",
                    "scale": 1,
                    "textWidth": "244.14231120925666px",
                    "compHeight": "16px"
                },
                "text": "2017",
                "textStyle": {
                    "color": "rgba(47,48,48,1)",
                    "fontId": "",
                    "font-weight": "normal",
                    "text-decoration": "none",
                    "letter-spacing": "0.1em",
                    "font-size": "85px",
                    "font-family": "微软雅黑",
                    "line-height": 1,
                    "fontLzkSrc": "",
                    "font-style": "normal",
                    "opacity": 1,
                    "text-align": "center"
                },
                "begin": 0
            }, {
                "compCoverIsShow": false,
                "cost": 10,
                "compStyle": {
                    "rotate": "0",
                    "z_index": 3,
                    "top": "0px",
                    "left": "40.51723462621706px",
                    "width": "179.21084546211395px",
                    "opacity": 1
                },
                "isSelect": true,
                "animation": {
                    "typeIn": "",
                    "typeOut": "",
                    "emphasisTime": 0,
                    "emphasisType": "",
                    "isLoop": false,
                    "typeInTime": 0.5,
                    "typeOutTime": 0.5
                },
                "compType": "wordComp",
                "bgColor": "rgba(255,255,255,0)",
                "unique": "41721e8c7fb147f48528d143daf8a215",
                "belongTo": "879b69c28e894fbb848de890ae32d42a",
                "editStyle": {
                    "textHeight": "16px",
                    "scale": 1,
                    "textWidth": "179.21084546211395px",
                    "compHeight": "16px"
                },
                "text": "BUSINESS&nbsp;TEMPLATE",
                "textStyle": {
                    "color": "rgba(47,48,48,1)",
                    "fontId": "",
                    "font-weight": "normal",
                    "text-decoration": "none",
                    "letter-spacing": "0em",
                    "font-size": "14px",
                    "font-family": "微软雅黑",
                    "line-height": 1,
                    "fontLzkSrc": "",
                    "font-style": "normal",
                    "opacity": 1,
                    "text-align": "center"
                },
                "begin": 0
            }, {
                "compCoverIsShow": false,
                "cost": 10,
                "compStyle": {
                    "rotate": "0",
                    "z_index": 4,
                    "top": "97.65692448370268px",
                    "left": "7.272324163679987px",
                    "width": "249.85628019500527px",
                    "opacity": 1
                },
                "isSelect": true,
                "animation": {
                    "typeIn": "",
                    "typeOut": "",
                    "emphasisTime": 0,
                    "emphasisType": "",
                    "isLoop": false,
                    "typeInTime": 0.5,
                    "typeOutTime": 0.5
                },
                "compType": "wordComp",
                "bgColor": "rgba(255,255,255,0)",
                "unique": "aef32e89e5c744a589a881d0cb122eb6",
                "belongTo": "879b69c28e894fbb848de890ae32d42a",
                "editStyle": {
                    "textHeight": "16px",
                    "scale": 1,
                    "textWidth": "249.85628019500527px",
                    "compHeight": "16px"
                },
                "text": "商&nbsp;务&nbsp;总&nbsp;结&nbsp;汇&nbsp;报&nbsp;使&nbsp;用&nbsp;模&nbsp;版",
                "textStyle": {
                    "color": "rgba(47,48,48,1)",
                    "fontId": "",
                    "font-weight": "normal",
                    "text-decoration": "none",
                    "letter-spacing": "0em",
                    "font-size": "15px",
                    "font-family": "微软雅黑",
                    "line-height": 1,
                    "fontLzkSrc": "",
                    "font-style": "normal",
                    "opacity": 1,
                    "text-align": "center"
                },
                "begin": 0
            }, {
                "compCoverIsShow": false,
                "cost": 10,
                "compStyle": {
                    "rotate": "0",
                    "z_index": 5,
                    "top": "123.6295107825598px",
                    "left": "50.90626914575991px",
                    "width": "162.5883902308454px",
                    "opacity": 1
                },
                "isSelect": true,
                "animation": {
                    "typeIn": "",
                    "typeOut": "",
                    "emphasisTime": 0,
                    "emphasisType": "",
                    "isLoop": false,
                    "typeInTime": 0.5,
                    "typeOutTime": 0.5
                },
                "compType": "wordComp",
                "bgColor": "rgba(255,255,255,0)",
                "unique": "ca9d6992834f4ed0a277ead8e9655202",
                "belongTo": "879b69c28e894fbb848de890ae32d42a",
                "editStyle": {
                    "textHeight": "16px",
                    "scale": 1,
                    "textWidth": "162.5883902308454px",
                    "compHeight": "16px"
                },
                "text": "https://www.zhi-niao.com/",
                "textStyle": {
                    "color": "rgba(47,48,48,1)",
                    "fontId": "",
                    "font-weight": "normal",
                    "text-decoration": "none",
                    "letter-spacing": "0em",
                    "font-size": "12px",
                    "font-family": "微软雅黑",
                    "line-height": 1,
                    "fontLzkSrc": "",
                    "font-style": "normal",
                    "opacity": 1,
                    "text-align": "center"
                },
                "begin": 0
            }, {
                "compType": "shapeComp",
                "cost": 10,
                "compStyle": {
                    "rotate": "0",
                    "border_width": "0px",
                    "z_index": 6,
                    "turnY": 1,
                    "fillList": ["#2F3030"],
                    "turn": 1,
                    "border_color": "rgba(0,0,0,1)",
                    "fill": "",
                    "opacityList": ["1"],
                    "top": "125.00000000000001px",
                    "left": "34.00000000000001px",
                    "transparency": 1,
                    "width": "197.89009158187255px",
                    "opacity": 1,
                    "border_radius": "0px",
                    "box_shadow": "",
                    "height": "2px"
                },
                "unique": "754a38a493d94d94a8837ccb28c5c4a8",
                "belongTo": "879b69c28e894fbb848de890ae32d42a",
                "isSelect": true,
                "materialId": "17A04963912C4E55B8206E8AEAB5F9ED",
                "shapesvg": "%3Csvg%20style%3D%22fill%3A%20rgb(47%2C%2048%2C%2048)%3B%20fill-opacity%3A%201%3B%22%20data-type%3D%22line%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22100%25%22%20height%3D%22100%25%22%20data-color0%3D%22color%22%3E%09%3Cg%20id%3D%22vscale%22%20transform%3D%22matrix(1%200%200%200.2%200%200)%22%3E%09%09%3Cdefs%3E%09%09%09%3Cpattern%20width%3D%222000%22%20height%3D%2210%22%20patternUnits%3D%22userSpaceOnUse%22%20id%3D%22shapeFilter1%22%20viewBox%3D%220%200%202000%2010%22%20overflow%3D%22visible%22%3E%09%09%09%09%3Crect%20width%3D%222000%22%20height%3D%2210%22%3E%3C%2Frect%3E%09%09%09%3C%2Fpattern%3E%09%09%3C%2Fdefs%3E%09%09%3Crect%20fill%3D%22url(%23shapeFilter1)%22%20width%3D%222000%22%20height%3D%2210%22%3E%3C%2Frect%3E%09%3C%2Fg%3E%3C%2Fsvg%3E",
                "begin": 0,
                "animation": {
                    "typeIn": "",
                    "typeOut": "",
                    "emphasisTime": 0,
                    "emphasisType": "",
                    "isLoop": false,
                    "typeInTime": 0.5,
                    "typeOutTime": 0.5
                }
            }],
            "compType": "groupComp",
            "cost": 10,
            "compStyle": {
                "rotate": "0",
                "z_index": 6,
                "top": "90px",
                "left": "23px",
                "transparency": 1,
                "width": "259.10937500000006px",
                "turn": 1,
                "opacity": 1,
                "border_radius": "0%",
                "height": "152.265625px"
            },
            "tempGroupComp": false,
            "unique": "879b69c28e894fbb848de890ae32d42a",
            "isSelect": true,
            "materialId": "D1B51A99BDE3430DB7AEA6F3D5B4894F",
            "begin": 0,
            "animation": {
                "typeIn": "",
                "isEmphasisInit": false,
                "typeOut": "",
                "isInInit": false,
                "isOutInit": false,
                "emphasisTime": 0.5,
                "emphasisType": "",
                "isLoop": false,
                "typeInTime": 0.5,
                "typeOutTime": 0.5
            }
        }],
        "active": "",
        "changeTextStyle": 0,
        "video": [],
        "pageId": "p46e389f1ad074d28939f141a70a27890",
        "currentTime": 0,
        "pageType": "slide",
        "bgImageStyle": {"bgImagePosition": "", "bgImageSize": "", "bgImageLzkSrc": "", "materialId": ""},
        "themeColor": "rgba(255,255,255,0)",
        "pageNo": 0,
        "action": "",
        "audio": [],
        "changeFlag": 0,
        "gridFlag": false
    },
        {
        "groupCompList": [],
        "groupListInfo": [],
        "modelId": "",
        "totalTime": 10,
        "componentList": [{
            "activeIndex": 1,
            "compType": "multiTestComp",
            "unique": "5bceb9afebbd4861b4e880fab9d0bd2c",
            "isPass": false,
            "list": [{
                "multiple": false,
                "title": "",
                "choice": [{"checked": true, "id": "A", "userChoose": false, "value": ""}, {
                    "checked": false,
                    "id": "B",
                    "userChoose": false,
                    "value": ""
                }, {"checked": false, "id": "C", "userChoose": false, "value": ""}, {
                    "checked": false,
                    "id": "D",
                    "userChoose": false,
                    "value": ""
                }],
                "commited": false
            }],
            "setting": {
                "setTestFlag": false,
                "pageType": "test",
                "orderShow": true,
                "subject": "12",
                "showAnswer": false,
                "testTime": 0,
                "isNew": false,
                "passPercent": 80,
                "isRank": true
            }
        }],
        "active": "",
        "changeTextStyle": 0,
        "video": [],
        "pageId": "pfcf8d6776cdb403aa6db02c751555820",
        "currentTime": 0,
        "pageType": "test",
        "bgImageStyle": {"bgImagePosition": "", "bgImageSize": "", "bgImageLzkSrc": "", "materialId": ""},
        "themeColor": "rgba(255,255,255,0)",
        "pageNo": 1,
        "action": "",
        "audio": [],
        "changeFlag": 0,
        "gridFlag": false
    }, {
        "groupCompList": [],
        "groupListInfo": [],
        "modelId": "",
        "totalTime": 10,
        "componentList": [{
            "filterStyle": {"filter": "", "background": "transparent", "mixBlendMode": ""},
            "compType": "pictureComp",
            "cost": 10,
            "compStyle": {
                "rotate": "0",
                "border_width": "0px",
                "z_index": 1,
                "turnY": 1,
                "turn": 1,
                "border_color": "rgba(0,0,0,1)",
                "top": "20.000000000000004px",
                "left": "7.000000000000001px",
                "transparency": 1,
                "width": "167px",
                "opacity": 1,
                "border_radius": "0px",
                "box_shadow": "",
                "height": "68.00000000000001px"
            },
            "pictureLzkSrc": "cwtools/material/private/20171109/tnxl15102355991425083.png",
            "unique": "52022f83c9854e62ac602ffc81a983b6",
            "belongTo": "",
            "clipStyle": {"isClipPic": false, "w": 0, "x": 0, "h": 0, "y": 0, "clipType": "", "clipRatio": ""},
            "isSelect": true,
            "materialId": "",
            "begin": 0,
            "animation": {
                "typeIn": "",
                "typeOut": "",
                "emphasisTime": 0.5,
                "emphasisType": "",
                "isLoop": false,
                "typeInTime": 0.5,
                "typeOutTime": 0.5
            }
        }, {
            "filterStyle": {"filter": "", "background": "transparent", "mixBlendMode": ""},
            "compType": "pictureComp",
            "cost": 10,
            "compStyle": {
                "rotate": "0",
                "border_width": "0px",
                "z_index": 2,
                "turnY": 1,
                "turn": 1,
                "border_color": "rgba(0,0,0,1)",
                "top": "107.00000000000001px",
                "left": "76px",
                "transparency": 1,
                "width": "129px",
                "opacity": 1,
                "border_radius": "0px",
                "box_shadow": "",
                "height": "119px"
            },
            "pictureLzkSrc": "cwtools/material/private/20171109/tn5h151023538100170761.png",
            "unique": "fc494aed33724fa08c240d2321e2573e",
            "belongTo": "",
            "clipStyle": {"isClipPic": false, "w": 0, "x": 0, "h": 0, "y": 0, "clipType": "", "clipRatio": ""},
            "isSelect": true,
            "materialId": "",
            "begin": 0,
            "animation": {
                "typeIn": "",
                "typeOut": "",props: ['pageData','pageImageStyle','currentPageNo','currentTime','courseWare','totalTime','loadPageNo','sendPostAjax','userInfo','clientHeight','isPreview'],

                "emphasisTime": 0.5,
                "emphasisType": "",
                "isLoop": false,
                "typeInTime": 0.5,
                "typeOutTime": 0.5
            }
        }, {
            "filterStyle": {"filter": "", "background": "transparent", "mixBlendMode": ""},
            "compType": "pictureComp",
            "cost": 10,
            "compStyle": {
                "rotate": "0",
                "border_width": "0px",
                "z_index": 3,
                "turnY": 1,
                "turn": 1,
                "border_color": "rgba(0,0,0,1)",
                "top": "220.00000000000003px",
                "left": "56.00000000000001px",
                "transparency": 1,
                "width": "101.00000000000001px",
                "opacity": 1,
                "border_radius": "0px",
                "box_shadow": "",
                "height": "105.00000000000001px"
            },
            "pictureLzkSrc": "cwtools/material/private/20171109/tnkv151023559096543606.png",
            "unique": "46cd6a1021af4f76a431819a7ed0301e",
            "belongTo": "",
            "clipStyle": {"isClipPic": false, "w": 0, "x": 0, "h": 0, "y": 0, "clipType": "", "clipRatio": ""},
            "isSelect": true,
            "materialId": "",
            "begin": 0,
            "animation": {
                "typeIn": "",
                "typeOut": "",
                "emphasisTime": 0.5,
                "emphasisType": "",
                "isLoop": false,
                "typeInTime": 0.5,
                "typeOutTime": 0.5
            }
        }, {
            "filterStyle": {"filter": "", "background": "transparent", "mixBlendMode": ""},
            "compType": "pictureComp",
            "cost": 10,
            "compStyle": {
                "rotate": "0",
                "border_width": "0px",
                "z_index": 4,
                "turnY": 1,
                "turn": 1,
                "border_color": "rgba(0,0,0,1)",
                "top": "382.00000000000006px",
                "left": "114.00000000000001px",
                "transparency": 1,
                "width": "132px",
                "opacity": 1,
                "border_radius": "0px",
                "box_shadow": "",
                "height": "129px"
            },
            "pictureLzkSrc": "cwtools/material/private/20171109/tny4151023559691231287.png",
            "unique": "8a4982334892408680785f439e4f701d",
            "belongTo": "",
            "clipStyle": {"isClipPic": false, "w": 0, "x": 0, "h": 0, "y": 0, "clipType": "", "clipRatio": ""},
            "isSelect": true,
            "materialId": "",
            "begin": 0,
            "animation": {
                "typeIn": "",
                "typeOut": "",
                "emphasisTime": 0.5,
                "emphasisType": "",
                "isLoop": false,
                "typeInTime": 0.5,
                "typeOutTime": 0.5
            }
        }, {
            "filterStyle": {"filter": "", "background": "transparent", "mixBlendMode": ""},
            "compType": "pictureComp",
            "cost": 10,
            "compStyle": {
                "rotate": "0",
                "border_width": "0px",
                "z_index": 5,
                "turnY": 1,
                "turn": 1,
                "border_color": "rgba(0,0,0,1)",
                "top": "309px",
                "left": "-44.00000000000001px",
                "transparency": 1,
                "width": "176.00000000000003px",
                "opacity": 1,
                "border_radius": "0px",
                "box_shadow": "",
                "height": "202.00000000000003px"
            },
            "pictureLzkSrc": "cwtools/material/private/20171109/tnf7151023559450690586.png",
            "unique": "ed2517a082324d5eb803c9d8a327ccd9",
            "belongTo": "",
            "clipStyle": {"isClipPic": false, "w": 0, "x": 0, "h": 0, "y": 0, "clipType": "", "clipRatio": ""},
            "isSelect": true,
            "materialId": "",
            "begin": 0,
            "animation": {
                "typeIn": "",
                "typeOut": "",
                "emphasisTime": 0.5,
                "emphasisType": "",
                "isLoop": false,
                "typeInTime": 0.5,
                "typeOutTime": 0.5
            }
        }],
        "active": "",
        "changeTextStyle": 0,
        "video": [],
        "pageId": "p6ba8eeddf87a484aabd18565e3753df2",
        "currentTime": 0,
        "pageType": "slide",
        "bgImageStyle": {"bgImagePosition": "", "bgImageSize": "", "bgImageLzkSrc": "", "materialId": ""},
        "themeColor": "rgba(255,255,255,0)",
        "pageNo": 2,
        "action": "",
        "audio": [],
        "changeFlag": 0,
        "gridFlag": false
    }],
    "coverPicLzkSrc": "",
    "autoPager": "0"
}